#
# We'll probably have a config file per customer project that we can import
# the required templates
#

imports:
- path: gce_instance.py

resources:
- name: vm
  type: gce_instance.py
  properties:
    machineType: f1-micro
    zone: us-central1-a
    image_project: debian-cloud
    image_name: debian-9
    labels:
      ansible_group: stackdriver_monitored
    metadata_items:
    - key: startup-script
      value: apt-get update; unattended-upgrade -v; apt-get install netcat -qy
    rs-Environment: testing
    rs-Role: instance
    rs-Application: rs_stl
    rs-CostCenter: rs-mgcp
    #rs-TemplatCommit: (we will need to add this through templating as it can't be passed through the command-line)
    rs-Team: rs-mgcp-ops
    rs-Component: instance
    #rs-PrimaryContact: (all rs-* fields optional, this is just to prove that)
