imports:
- path: cluster.py

resources:
- type: cluster.py
  name: cluster1
  properties:
    initialNodeCount: 1
    machine_type: n1-standard-1
    oauthScopes:
    - devstorage.read_only
    - compute
    - logging.write
    - monitoring
    zone: us-central1-a
#    - us-central1-a
#    - us-central1-b
#    - us-central1-c
    disk_size_gb: 10
    autoscaling:
      enabled: true
      minNodeCount: 1
      maxNodeCount: 2