imports:
- path: cluster.py
- path: network.py

resources:
- name: vpc-network
  type: network.py
  properties:
    net_name: smash-network
    subnet_names:
    - subnet-1
    subnet_regions:
    - us-central1
    subnet_ranges:
    - 10.1.0.0/20

- type: cluster.py
  name: cluster1
  properties:
    #per zone
    initial_node_count: 1
    machine_type: n1-standard-1
    oauth_scopes:
    - devstorage.read_only
    - compute
    - logging.write
    - monitoring
    - bigquery
    zone: us-central1-a
    vpc_network: $(ref.smash-network.selfLink)
    subnetwork: $(ref.subnet-1.selfLink)
    os_image_type: COS
    disk_size_gb: 10
    preemptible: false
    autoscaling:
      enabled: true
      #per zone
      minNodeCount: 1
      maxNodeCount: 2
    management:
      autoUpgrade: false
      autoRepair: false
      upgradeOptions: {}
    #pass this in if you want to
    #have a multi regional cluster
    locations:
    - us-central1-a
    - us-central1-b
    - us-central1-c