imports:
- path: gce_instancetemplate.py

resources:
- type: gce_instancetemplate.py
  name: gce-instancetemplate-test
  properties:
    machineType: f1-micro
    image_url: 'https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9'
    networkInterfaces:
    - accessConfigs:
        - { name: external-nat, type: ONE_TO_ONE_NAT }
    tags:
      - webapp
    serviceAccounts:
    - scopes:
      - devstorage.read_only
      - logging.write
      - monitoring.write
      - servicecontrol
      - service.management.readonly
      - trace.append
    rs-Environment: testing
    rs-Role: instancetemplate
    rs-Application: rs_stl
    rs-CostCenter: rs-mgcp
    #rs-TemplatCommit: (we will need to add this through templating as it can't be passed through the command-line)
    rs-Team: rs-mgcp-ops
    rs-Component: instancetemplate
    #rs-PrimaryContact: (all rs-* fields optional, this is just to prove that)
