imports:
- path: cluster.py
- path: network.py
- path: cloudsql.py
- path: enable_apis.py

resources:
- name: apis
  type: enable_apis.py
  properties:
    apis:
      - deploymentmanager.googleapis.com
      - pubsub.googleapis.com
      - sql-component.googleapis.com
      - container.googleapis.com
      - bigquery-json.googleapis.com
      - datastore.googleapis.com

- name: vpc-network
  type: network.py
  properties:
    net_name: smash-network
    subnet_names:
    - subnet-1
    subnet_regions:
    - us-central1
    subnet_ranges:
    - 10.1.0.0/20

- name: cloudsql
  type: cloudsql.py
  properties:
    name: cloudsql-test-template1
    region: us-central1
    #Prefered zone
    location_preference:
      zone: us-central1-a
    ip-configuration:
      #Authorized networks to connect to cloudsql instance
      authorizedNetworks:
      - name: subnet-a
        value: 199.27.25.0/24
    db_machine_type: db-n1-standard-1
    db_version: MYSQL_5_6
    # Can be CLOUD_SQL_INSTANCE or READ_REPLICA_INSTANCE
    instance_type: CLOUD_SQL_INSTANCE
    failover_replica:
      #Failover read replica name
      name: cloudsql-test-template1-failover
    backup_configuration:
      kind: sql#backupConfiguration
      #UTC timezone in the 24 hour format - HH:MM
      startTime: 01:00
      enabled: true
      binaryLogEnabled: true
    ##
    ##We are not passing Root password from here, as it gets saved in github and deployment-manager console
    ##Create a sql resource without password, login to console, generate password and save it password-safe
    ##
    backend_type: SECOND_GEN
    data_disk_type: PD_SSD
    data_disk_size: 25

- type: cluster.py
  name: cluster1
  properties:
    #per zone
    initial_node_count: 1
    machine_type: n1-standard-1
    oauth_scopes:
    - devstorage.read_only
    - compute
    - logging.write
    - monitoring
    - bigquery
    zone: us-central1-a
    vpc_network: $(ref.smash-network.selfLink)
    subnetwork: $(ref.subnet-1.selfLink)
    os_image_type: COS
    disk_size_gb: 10
    preemptible: false
    autoscaling:
      enabled: true
      #per zone
      minNodeCount: 1
      maxNodeCount: 2
    management:
      autoUpgrade: false
      autoRepair: false
      upgradeOptions: {}
    #pass this in if you want to
    #have a multi regional cluster
    locations:
    - us-central1-a
    - us-central1-b
    - us-central1-c